/**
 * Envio HyperIndex event handlers for SpeakUpRegistry.
 *
 * Run locally:
 *   cd packages/indexer
 *   pnpm envio codegen
 *   pnpm envio dev
 *
 * Hosted: push to envio.dev and connect this repo.
 *
 * Type imports are generated by `envio codegen` from config.yaml + schema.graphql;
 * the import paths below match Envio's standard generated layout.
 */
import {
  SpeakUpRegistry,
  type Ticker,
  type Meeting,
  type Vote,
  type Voter,
  type ItemTally,
  type RelayerChange,
} from 'generated';

const CHOICE_LABEL = ['ABSTAIN', 'FOR', 'AGAINST'] as const;

function ascii(hex: string): string {
  // Convert a left-padded bytes32 ascii literal back to a string,
  // stripping null bytes. Used for human-readable ticker / meeting ids.
  const clean = hex.startsWith('0x') ? hex.slice(2) : hex;
  let out = '';
  for (let i = 0; i < clean.length; i += 2) {
    const b = parseInt(clean.slice(i, i + 2), 16);
    if (b === 0) break;
    out += String.fromCharCode(b);
  }
  return out;
}

SpeakUpRegistry.TickerRegistered.handler(async ({ event, context }) => {
  const id = event.params.ticker;
  const ticker: Ticker = {
    id,
    symbol: ascii(id),
    token: event.params.token,
    cik: event.params.cik,
    active: true,
    registeredAt: BigInt(event.block.timestamp),
  };
  context.Ticker.set(ticker);
});

SpeakUpRegistry.TickerDeactivated.handler(async ({ event, context }) => {
  const existing = await context.Ticker.get(event.params.ticker);
  if (!existing) return;
  context.Ticker.set({ ...existing, active: false });
});

SpeakUpRegistry.MeetingRegistered.handler(async ({ event, context }) => {
  const id = event.params.meetingId;
  const meeting: Meeting = {
    id,
    label: ascii(id),
    ticker_id: event.params.ticker,
    voteOpen: event.params.voteOpen,
    voteDeadline: event.params.voteDeadline,
    defUrl: event.params.defUrl,
    active: true,
    registeredAt: BigInt(event.block.timestamp),
    totalVotes: 0,
    totalWeight: 0n,
    forCount: 0,
    againstCount: 0,
    abstainCount: 0,
  };
  context.Meeting.set(meeting);
});

SpeakUpRegistry.MeetingClosed.handler(async ({ event, context }) => {
  const existing = await context.Meeting.get(event.params.meetingId);
  if (!existing) return;
  context.Meeting.set({ ...existing, active: false });
});

SpeakUpRegistry.VoteCast.handler(async ({ event, context }) => {
  const voterAddr = event.params.voter.toLowerCase();
  const choice = Number(event.params.choice);

  // Upsert voter
  const existingVoter = await context.Voter.get(voterAddr);
  const voter: Voter = existingVoter
    ? {
        ...existingVoter,
        totalVotes: existingVoter.totalVotes + 1,
        totalWeight: existingVoter.totalWeight + event.params.weight,
      }
    : {
        id: voterAddr,
        address: voterAddr,
        firstSeenAt: BigInt(event.block.timestamp),
        totalVotes: 1,
        totalWeight: event.params.weight,
      };
  context.Voter.set(voter);

  // Insert vote
  const vote: Vote = {
    id: event.params.uid,
    uid: event.params.uid,
    voter_id: voter.id,
    meeting_id: event.params.meetingId,
    itemId: Number(event.params.itemId),
    choice,
    choiceLabel: CHOICE_LABEL[choice] ?? `UNKNOWN_${choice}`,
    weight: event.params.weight,
    reasoningHash: '0x', // populated below if stored separately
    castAt: BigInt(event.block.timestamp),
    castTxHash: event.transaction.hash,
    status: 0, // PENDING
    ackRef: undefined,
    ackedAt: undefined,
    ackTxHash: undefined,
  };
  context.Vote.set(vote);

  // Update meeting aggregates
  const meeting = await context.Meeting.get(event.params.meetingId);
  if (meeting) {
    const next: Meeting = {
      ...meeting,
      totalVotes: meeting.totalVotes + 1,
      totalWeight: meeting.totalWeight + event.params.weight,
      forCount: meeting.forCount + (choice === 1 ? 1 : 0),
      againstCount: meeting.againstCount + (choice === 2 ? 1 : 0),
      abstainCount: meeting.abstainCount + (choice === 0 ? 1 : 0),
    };
    context.Meeting.set(next);
  }

  // Per-item tally
  const tallyId = `${event.params.meetingId}-${event.params.itemId}`;
  const existingTally = await context.ItemTally.get(tallyId);
  const tally: ItemTally = existingTally
    ? {
        ...existingTally,
        forWeight: existingTally.forWeight + (choice === 1 ? event.params.weight : 0n),
        againstWeight:
          existingTally.againstWeight + (choice === 2 ? event.params.weight : 0n),
        abstainWeight:
          existingTally.abstainWeight + (choice === 0 ? event.params.weight : 0n),
        forCount: existingTally.forCount + (choice === 1 ? 1 : 0),
        againstCount: existingTally.againstCount + (choice === 2 ? 1 : 0),
        abstainCount: existingTally.abstainCount + (choice === 0 ? 1 : 0),
      }
    : {
        id: tallyId,
        meeting_id: event.params.meetingId,
        itemId: Number(event.params.itemId),
        forWeight: choice === 1 ? event.params.weight : 0n,
        againstWeight: choice === 2 ? event.params.weight : 0n,
        abstainWeight: choice === 0 ? event.params.weight : 0n,
        forCount: choice === 1 ? 1 : 0,
        againstCount: choice === 2 ? 1 : 0,
        abstainCount: choice === 0 ? 1 : 0,
      };
  context.ItemTally.set(tally);
});

SpeakUpRegistry.VoteAcknowledged.handler(async ({ event, context }) => {
  const existing = await context.Vote.get(event.params.uid);
  if (!existing) return;
  context.Vote.set({
    ...existing,
    status: Number(event.params.status),
    ackRef: event.params.ackRef,
    ackedAt: BigInt(event.block.timestamp),
    ackTxHash: event.transaction.hash,
  });
});

SpeakUpRegistry.RelayerUpdated.handler(async ({ event, context }) => {
  const change: RelayerChange = {
    id: event.transaction.hash,
    oldRelayer: event.params.oldRelayer.toLowerCase(),
    newRelayer: event.params.newRelayer.toLowerCase(),
    changedAt: BigInt(event.block.timestamp),
  };
  context.RelayerChange.set(change);
});
